### ISSUE TITLE
Current release disabled on mobile

### ISSUE THREAD

**Issue by meganleewebb** [ravimashru/obsidian-show-file-path#12]
I used the "copy path to clipboard" feature on Android. Current release only enables on desktop. Can it be revealed for mobile?

**Comment by ravimashru** [comment]
I enabled it for desktop only because it wasn't working as expected on the iPad (see https://github.com/ravimashru/obsidian-show-file-path/issues/9). I assumed it wouldn't work on Android either. My bad, I should have tested this.

I will publish a new version that enables it on mobile and maybe just write in the README that it doesn't work for iOS/iPadOS.

**Comment by meganleewebb** [comment]
On Android also, I do not see the path displayed with all options turned on. However my use case is running the copy path command, so I'd ignored the lack of - display on mobile.

**Comment by ravimashru** [comment]
Ah, I see. The copy path command doesn't work on iOS/iPadOS either :( But if the command works on Android it's worth keeping mobile support turned on. 🙂 

I just released 0.5.2 with mobile support turned back on.

**Comment by meganleewebb** [comment]
Thank you. I'm hoping that the next release of obsidian for mobile fixes the status barb for plugins.
